[env.dev]
name = "solidjs-dev"
type = "webpack"
account_id = ""
workers_dev = true
route = "dev.solidjs.com/*"
zone_id = ""

[env.prod]
name = "solidjs"
type = "webpack"
account_id = ""
workers_dev = false
route = "www.solidjs.com/*"
zone_id = ""

[site]
bucket = "./dist"
entry-point = "workers-site"
